module.exports = {
  relative: { key: 'position', val: 'relative' },
  'static': { key: 'position', val: 'static' },
  absolute: { key: 'position', val: 'absolute' },
  fixed: { key: 'position', val: 'fixed' },
  sticky: { key: 'position', val: 'sticky' },
  block: { key: 'display', val: 'block' },
  none: { key: 'display', val: 'none' },
  visible: { key: 'visibility', val: 'visible' },
  hidden: { key: 'visibility', val: 'hidden' },
  collapsible: { key: 'visibility', val: 'collapse' },
  rtl: { key: 'direction', val: 'rtl' },
  ltr: { key: 'direction', val: 'ltr' },
  isolate: { key: 'isolation', val: 'isolate' },
  isolation: { key: 'isolation', val: 'auto' },
  nowrap: { key: 'white-space', val: 'nowrap' },
  pre: { key: 'white-space', val: 'pre' },
  preline: { key: 'white-space', val: 'pre-line' },
  prewrap: { key: 'white-space', val: 'pre-wrap' },
  wrap: { key: 'overflow-wrap', val: 'break-word' },
  anywhere: { key: 'overflow-wrap', val: 'anywhere' },
  breakall: { key: 'word-break', val: 'break-all' },
  'break': { key: 'word-break', val: 'break-word' },
  noselect: { key: 'user-select', val: 'none' },
  userselect: { key: 'user-select', val: 'text' },
  selectall: { key: 'user-select', val: 'all' },
}
