module.exports = {
  w: 'width',
  h: 'height',
  d: 'display',
  z: 'zIndex',
  m: 'margin',
  p: 'padding',
  mt: 'marginTop',
  me: 'marginRight',
  mr: 'marginRight',
  mb: 'marginBottom',
  ms: 'marginLeft',
  ml: 'marginLeft',
  bd: 'border',
  bg: 'background',
  fg: 'color',
  ff: 'fontFamily',
  fs: 'fontSize',
  fw: 'fontWeight',
  fv: 'fontVariant',
  fw: 'fontWeight',
  fe: 'fontStretch',
  fi: 'fontStyle',
  lh: 'lineHeight',
  align: 'textAlign',
  justify: 'justifyContent',
  items: 'alignItems'
}
